libs:
  _include: (fitstoolz.apps.parser_configs)base.yaml

inputs:
  _use:
  - libs.base.inputs
  - libs.chunking.inputs
  axis:
    info: Stack files along this axis
    dtype: str
  extra-files:
    info: Additional files to stack (use multiple times)
    dtype: List[str]
    policies:
      repeat: repeat

outputs:
  _use:
  - libs.base.outputs
  stacked-fits:
    info: Path of stacked output image
    dtype: File
