base:
  inputs:
    fname:
      info: Input file(s)
      dtype: File
      required: true
      policies:
        positional: true
    replace:
      info: Overwrite output if it exists
      dtype: bool
      policies:
        is_flag: true

  outputs:
    outfile:
      info: Path of output image 
      dtype: File

chunking:
  inputs:
    ra-chunks:
      info: RA chunking
      dtype: int
      default: null
    dec-chunks:
      info: Dec chunking
      dtype: int
      default: null
    spectral-chunks:
      info: spectral chunking
      dtype: int
      default: null
    temporal-chunks:
      info: RA chunking
      dtype: int
      default: null

fits_axis:
  inputs:
    ctype:
      info: Axis type; FREQ, STOKES, etc.
      dtype: str
    index:
      info: Add axis at this dimension index
      dtype: int
    crpix:
      info: Reference pixel (zero-based indexing)
      dtype: int
    crval:
      info: Value at Reference pixel (crval)
      dtype: float
    cdelt:
      info: Pixel width
      dtype: float
    cunit:
      info: Units (astropy naming convention)
      dtype: str
